import { Notice } from "./ui";

// Fixed messages only: the URL carries a code, never free text.
const MESSAGES: Record<string, { tone: "success" | "info" | "warn" | "danger"; text: string }> = {
  salvato: { tone: "success", text: "Salvato." },
  preparata: { tone: "success", text: "Candidatura pronta: controllala e premi Invia." },
  "in-coda": { tone: "success", text: "In coda. Parte tra almeno 15 minuti: fino ad allora puoi annullare." },
  "tutte-in-coda": { tone: "success", text: "In coda. Partiranno una alla volta, distanziate tra loro." },
  annullata: { tone: "info", text: "Invio annullato. La candidatura è tornata tra quelle da inviare." },
  saltata: { tone: "info", text: "Messa da parte." },
  fermati: { tone: "warn", text: "Invii fermati. Niente partirà finché non li riattivi." },
  ripartiti: { tone: "success", text: "Invii di nuovo attivi." },
  scartata: { tone: "success", text: "Cancellata: non te la ripropongo più (né da quel link né lo stesso annuncio su un altro sito). Se era un errore, la trovi in “Non mi interessano” in fondo a Offerte: puoi annullare per 3 giorni." },
  candidata: { tone: "success", text: "Candidatura segnata come inviata." },
  "copiato-prompt": { tone: "success", text: "Testo copiato. Incollalo nella chat di Claude." },
  "testo-salvato": { tone: "success", text: "Testo salvato." },
  "usa-il-sito": { tone: "info", text: "Questa offerta non accetta candidature via e-mail: candidati sul sito con il kit qui sotto." },
  "stato-aggiornato": { tone: "success", text: "Candidatura aggiornata." },
  "cv-caricato": { tone: "success", text: "CV caricato." },
  "posizioni-salvate": { tone: "success", text: "Posizioni salvate: le prossime ricerche useranno queste." },
  "posizioni-vuote": { tone: "warn", text: "Nessuna posizione spuntata: le ricerche useranno solo settori e aziende scelti." },
  "carriere-salvate": { tone: "success", text: "Salvato: ora cerco in tutte queste carriere e in tutti questi paesi. Il web scraping parte da solo (se non l'hai lanciato negli ultimi 10 minuti)." },
  "scartata-lista": { tone: "success", text: "Cancellata: non te la ripropongo più. Se era un errore, la trovi in “Non mi interessano” in fondo alla pagina: puoi annullare per 3 giorni." },
  "scarto-annullato": { tone: "success", text: "Annullato: se l'offerta è ancora in giro torna nella tua lista, e potrà esserti riproposta." },
  "solo-titolare": { tone: "warn", text: "Solo la persona titolare può eliminare il proprio account. Da amministratore usa Admin → Utenti." },
  "conferma-elimina": { tone: "warn", text: "Per confermare scrivi ELIMINA nel campo." },
  "password-sbagliata": { tone: "warn", text: "La password non è corretta." },
  "scegli-situazione": { tone: "warn", text: "Scegli prima cosa fai ora: serve a farti le domande giuste." },
  "gmail-collegata": { tone: "success", text: "Gmail collegata. Sto leggendo gli avvisi degli ultimi 10 giorni (quelli più vecchi spesso sono già scaduti): le offerte arrivano tra poco in Offerte." },
  "gmail-scollegata": { tone: "success", text: "Gmail scollegata: Compass non può più leggerla e il permesso è stato tolto anche su Google." },
  "gmail-annullato": { tone: "info", text: "Collegamento annullato: quando vuoi, riprova." },
  "gmail-permesso-mancante": { tone: "warn", text: "Google non ha dato il permesso di leggere le e-mail: riprova e lascia spuntata la casella \"Visualizzare i tuoi messaggi email\"." },
  "gmail-riprova": { tone: "warn", text: "Il collegamento con Google non è andato a buon fine: riprova." },
  "gmail-non-disponibile": { tone: "warn", text: "\"Collega Gmail\" non è ancora attivo: usa l'inoltro qui sotto, oppure chiedi all'amministratore." },
  "casella-collegata": { tone: "success", text: "Fatto: Compass legge già la tua Gmail, niente inoltro. Ora gli account." },
  "casella-non-tua": { tone: "warn", text: "Questa casella è collegata a un altro account: chiedi all'amministratore di collegarla al tuo (Admin → Utenti → Casella)." },
  "controllo-avviato": { tone: "success", text: "Sto leggendo la casella di Compass: la pagina si aggiorna da sola." },
  "dove-salvato": { tone: "success", text: "Salvato: cerco in questi posti. Il web scraping parte da solo (se non l'hai lanciato negli ultimi 10 minuti)." },
  "ricerca-avviata": { tone: "success", text: "Web scraping avviato: siti delle aziende, pagine lavoro e ricerca sul web. Le offerte compaiono qui entro un minuto." },
  "ricerche-finite": { tone: "info", text: "Hai usato le ricerche a mano di oggi: il conto alla rovescia dice quando torna la prossima. La ricerca automatica continua ogni mattina." },
  "ricerca-attendi": { tone: "info", text: "Aspetta il conto alla rovescia per la prossima ricerca. Con Plus o Premium sono più spesso." },
  "piano-attivo": { tone: "success", text: "Piano attivato in prova gratuita: nessun addebito. Le ricerche in più valgono da subito." },
  "piano-free": { tone: "success", text: "Sei sul piano Free." },
  "ricerca-recente": { tone: "info", text: "Hai già cercato da poco: riprova tra 10 minuti. Intanto la ricerca continua ogni mattina." },
  "punteggio-salvato": { tone: "success", text: "Salvato: punteggi ricalcolati." },
  "salvata-in-cartella": { tone: "success", text: "Salvata nella cartella." },
  "tolta-da-cartella": { tone: "info", text: "Tolta dalla cartella." },
  "cartella-creata": { tone: "success", text: "Cartella creata." },
  "cartella-rinominata": { tone: "success", text: "Cartella rinominata." },
  "cartella-eliminata": { tone: "info", text: "Cartella eliminata (le offerte restano in Offerte)." },
  "spontanea-pronta": { tone: "success", text: "Candidatura spontanea pronta: rileggila e inviala da qui." },
  "dati-non-validi": { tone: "warn", text: "Controlla l'indirizzo e-mail e il link della pagina." },
  "cv-troppo-grande": { tone: "warn", text: "Il file supera 2 MB. Esporta un PDF più leggero e riprova." },
  "cv-non-pdf": { tone: "warn", text: "Serve un file PDF. Esporta il documento in PDF e riprova." },
  "cv-troppi": { tone: "warn", text: "Massimo 3 CV: eliminane uno prima di caricarne un altro." },
  aggiunta: { tone: "success", text: "Offerta aggiunta." },
  "dati-cancellati": { tone: "success", text: "Tutti i tuoi dati sono stati cancellati." },
  bloccata: { tone: "warn", text: "Questa candidatura non può partire: il motivo è sulla scheda." },
  importati: { tone: "success", text: "Importazione completata." },
  "serve-riassunto": { tone: "warn", text: "Prima di approvare un sito scrivi il riassunto dei termini d'uso e quello di robots.txt." },
  "password-corta": { tone: "warn", text: "La password deve avere almeno 10 caratteri." },
  "risposta-simulata": { tone: "success", text: "Risposta simulata ricevuta: guarda Candidature." },
  "coda-svuotata": { tone: "success", text: "Coda inviata (in modalità prova, nell'outbox qui sotto)." },
  "eseguito-ingest": { tone: "success", text: "Raccolta offerte eseguita." },
  "eseguito-discover": { tone: "success", text: "Ricerca sul web (W1) eseguita." },
  "eseguito-queue": { tone: "success", text: "Coda degli invii controllata." },
  "eseguito-replies": { tone: "success", text: "Casella controllata per le risposte." },
  "eseguito-digest": { tone: "success", text: "E-mail del mattino preparata." },
  preferenze: { tone: "success", text: "Preferenze salvate. Le offerte sono state riordinate." },
  "altro-aggiunto": { tone: "success", text: "Aggiunto al tuo elenco." },
  "filtri-salvati": { tone: "success", text: "Filtri salvati come predefiniti." },
  registrato: { tone: "success", text: "Account creato. Rispondi a qualche domanda per iniziare." },
  "account-creato": { tone: "success", text: "Account creato." },
  "invito-creato": { tone: "success", text: "Invito creato: copia il codice qui sotto, non verrà mostrato di nuovo." },
  "richiesta-approvata": { tone: "success", text: "Richiesta approvata: la persona può entrare e ha ricevuto un'e-mail." },
  "richiesta-rifiutata": { tone: "success", text: "Richiesta rifiutata e cancellata." },
  "account-eliminato": { tone: "success", text: "Account eliminato con tutti i suoi dati." },
  "nessun-utente": { tone: "info", text: "Non ci sono ancora persone: crea il primo account." },
  "email-esistente": { tone: "warn", text: "Esiste già un account con questa e-mail." },
  "email-non-valida": { tone: "warn", text: "L'indirizzo e-mail non è valido." },
  "catalogo-salvato": { tone: "success", text: "Catalogo aggiornato." },
  "preferenze-attenzione": { tone: "warn", text: "Salvato. Questa azienda sembra lontana dal tuo percorso: trovi il motivo accanto al nome. Se è un cambio voluto, va benissimo." },
  "cv-caricato-esperienze": { tone: "success", text: "CV caricato. Ho letto le tue esperienze: le trovi in Profilo → Esperienze." },
  "cv-caricato-senza-testo": { tone: "info", text: "CV caricato, ma non riesco a leggerne il testo (forse è una scansione). Puoi incollarlo nei dettagli del CV." },
  "esperienze-lette": { tone: "success", text: "Esperienze importate. Controllale e correggi quello che non va." },
  "esperienze-nessuna": { tone: "warn", text: "Non ho trovato esperienze con delle date nel CV. Puoi aggiungerle a mano qui sotto." },
  "linkedin-niente": { tone: "warn", text: "Nel file non ho trovato Positions.csv o Education.csv. Carica lo .zip dell'esportazione di LinkedIn o quei due file." },
  errore: { tone: "danger", text: "Qualcosa non ha funzionato. Riprova tra un minuto." },
};

export function Flash({ code }: { code?: string | string[] }) {
  const c = Array.isArray(code) ? code[0] : code;
  const m = c ? MESSAGES[c] : undefined;
  if (!m) return null;
  return (
    <div className="mb-5">
      <Notice tone={m.tone}>{m.text}</Notice>
    </div>
  );
}
