// Official websites of the hand-made catalog's companies, for the web scraping of their career
// pages. Only domains we are sure of: a wrong one would read someone else's offers.
export const CURATED_WEBSITES: Record<string, string> = {
  // Investment banks and advisory boutiques
  Lazard: "lazard.com",
  "Rothschild & Co": "rothschildandco.com",
  "Houlihan Lokey": "hl.com",
  "Lincoln International": "lincolninternational.com",
  Alantra: "alantra.com",
  Equita: "equita.eu",
  Evercore: "evercore.com",
  "PJT Partners": "pjtpartners.com",
  "Moelis & Company": "moelis.com",
  "Perella Weinberg Partners": "pwpartners.com",
  "Centerview Partners": "centerviewpartners.com",
  "DC Advisory": "dcadvisory.com",
  Oaklins: "oaklins.com",
  "Clairfield International": "clairfield.com",
  "Arma Partners": "armapartners.com",
  Mediobanca: "mediobanca.com",
  "Intesa Sanpaolo": "group.intesasanpaolo.com",
  UniCredit: "unicreditgroup.eu",
  "Banca Akros": "bancaakros.it",
  Intermonte: "intermonte.it",
  "Goldman Sachs": "goldmansachs.com",
  "J.P. Morgan": "jpmorganchase.com",
  "Morgan Stanley": "morganstanley.com",
  "BofA Securities": "bankofamerica.com",
  Citi: "citigroup.com",
  Barclays: "home.barclays",
  "Deutsche Bank": "db.com",
  UBS: "ubs.com",
  "BNP Paribas": "group.bnpparibas",
  HSBC: "hsbc.com",
  Jefferies: "jefferies.com",
  Nomura: "nomura.com",
  "Société Générale": "societegenerale.com",
  "Crédit Agricole CIB": "ca-cib.com",
  // Private equity and asset management
  Permira: "permira.com",
  "CVC Capital Partners": "cvc.com",
  "Bain Capital": "baincapital.com",
  KKR: "kkr.com",
  Carlyle: "carlyle.com",
  Blackstone: "blackstone.com",
  EQT: "eqtgroup.com",
  Ardian: "ardian.com",
  Investindustrial: "investindustrial.com",
  Clessidra: "clessidra.it",
  "Fondo Italiano d'Investimento": "fondoitaliano.it",
  Eurizon: "eurizon.com",
  Amundi: "amundi.com",
  Anima: "animasgr.it",
  "Kairos Partners": "kairospartners.com",
  "Azimut Holding": "azimut-group.com",
  "Banca Mediolanum": "bancamediolanum.it",
  Fideuram: "fideuram.it",
  FinecoBank: "finecobank.com",
  Algebris: "algebris.com",
  BlackRock: "blackrock.com",
  Pictet: "group.pictet",
  // Consulting and deals
  "McKinsey & Company": "mckinsey.com",
  "Boston Consulting Group": "bcg.com",
  "Bain & Company": "bain.com",
  Kearney: "kearney.com",
  "L.E.K. Consulting": "lek.com",
  "Simon-Kucher": "simon-kucher.com",
  Bip: "bipgroup.com",
  Deloitte: "deloitte.com",
  KPMG: "kpmg.com",
  PwC: "pwc.com",
  EY: "ey.com",
  // Startups and fintech
  Satispay: "satispay.com",
  Scalapay: "scalapay.com",
  Moneyfarm: "moneyfarm.com",
  "Young Platform": "youngplatform.com",
  Qonto: "qonto.com",
  Revolut: "revolut.com",
  Stripe: "stripe.com",
  "Bending Spoons": "bendingspoons.com",
  Casavo: "casavo.com",
  "Prima Assicurazioni": "prima.it",
  Translated: "translated.com",
};
