"""Code-generated daily report (numbers come from code, never from an LLM's head).
Writes reports/daily/YYYY-MM-DD.{md,json}. The Claude daily reviewer reads these."""
from __future__ import annotations

import json
from pathlib import Path

import pandas as pd

from ..analytics.stats import sharpe, t_test_mean
from ..config import PROJECT_ROOT
from ..db import one


def build(con, settings, r_date: str) -> dict:
    rep: dict = {"date": r_date, "accounts": {}, "ops": {}, "signals": {}, "risk_events": []}
    for a in con.execute("SELECT * FROM accounts ORDER BY account_id").fetchall():
        acc = a["account_id"]
        eq = pd.read_sql_query("SELECT e_date, cost_model, equity, n_open, gross_exposure FROM equity_daily "
                               "WHERE account_id=? AND e_date<=? ORDER BY e_date", con, params=(acc, r_date))
        out = {"strategy": a["strategy_id"], "broker": a["broker"]}
        for m in ("opt", "pess"):
            e = eq[eq["cost_model"] == m].set_index("e_date")["equity"]
            if e.empty:
                continue
            r = e.pct_change().dropna()
            peak = e.cummax()
            out[m] = {"equity": round(float(e.iloc[-1]), 2),
                      "ret_today": float(r.iloc[-1]) if len(r) else None,
                      "ret_total": float(e.iloc[-1] / a["start_equity"] - 1),
                      "max_drawdown": float((e / peak - 1).min()),
                      "sharpe_ann": sharpe(r.values) if len(r) > 5 else None,
                      "n_days": int(len(e))}
        tr = pd.read_sql_query("SELECT * FROM trades WHERE account_id=? AND status='closed' AND exit_date<=?", con,
                               params=(acc, r_date))
        out["closed_trades"] = int(len(tr))
        out["open_positions"] = int(one(con, "SELECT COUNT(*) FROM trades WHERE account_id=? AND status IN "
                                             "('open','pending_exit')", (acc,)) or 0)
        if len(tr):
            out["net_ret_pess_per_trade"] = t_test_mean(tr["net_ret_pess"].tolist())
            out["hit_rate_pess"] = float((tr["net_ret_pess"] > 0).mean())
            out["closed_today"] = tr[tr["exit_date"] == r_date][
                ["trade_id", "symbol", "gross_ret", "net_ret_pess", "mae", "mfe", "exit_reason"]].to_dict("records")
        rep["accounts"][acc] = out
    rep["signals"] = {
        "today_total": one(con, "SELECT COUNT(*) FROM signals WHERE decision_date=?", (r_date,)),
        "today_traded": one(con, "SELECT COUNT(*) FROM signals WHERE decision_date=? AND traded=1", (r_date,)),
        "not_traded_reasons": [dict(r) for r in con.execute(
            "SELECT not_traded_reason, COUNT(*) n FROM signals WHERE decision_date=? AND traded=0 GROUP BY 1", (r_date,))],
        "outcomes_rows_total": one(con, "SELECT COUNT(*) FROM signal_outcomes"),
    }
    rep["ops"] = {
        "jobs_24h": [dict(r) for r in con.execute(
            "SELECT job, status, COUNT(*) n, MAX(finished_at) last FROM job_runs WHERE started_at>=datetime(?, '-1 day') "
            "GROUP BY job, status ORDER BY job", (r_date + " 23:59:59",))],
        "filings_today": one(con, "SELECT COUNT(*) FROM filings WHERE substr(available_at,1,10)=?", (r_date,)),
        "filings_missing_accept_ts": one(con, "SELECT COUNT(*) FROM filings WHERE accepted_ts IS NULL "
                                              "AND substr(ingested_at,1,10)=?", (r_date,)),
        "news_today": one(con, "SELECT COUNT(*) FROM news WHERE substr(created_ts,1,10)=?", (r_date,)),
        "bars_today": one(con, "SELECT COUNT(*) FROM bars_daily WHERE bar_date=?", (r_date,)),
        "universe_size": one(con, "SELECT COUNT(*) FROM universe_snapshots WHERE snap_date=? AND in_universe=1", (r_date,)),
        "open_data_gaps": one(con, "SELECT COUNT(*) FROM data_gaps WHERE resolved_at IS NULL"),
        "kill_flags": [dict(r) for r in con.execute("SELECT key, value FROM meta WHERE key LIKE 'kill:%'")],
    }
    rep["risk_events"] = [dict(r) for r in con.execute(
        "SELECT ts, account_id, kind, detail FROM risk_events WHERE substr(ts,1,10)>=date(?, '-1 day')", (r_date,))]
    return rep


def to_markdown(rep: dict) -> str:
    L = [f"# Daily report {rep['date']}", "", "Numbers generated by code. Costs: opt = optimistic, pess = pessimistic.", ""]
    L += ["| account | broker | equity pess | ret today pess | total pess | total opt | maxDD pess | closed | open |",
          "|---|---|---|---|---|---|---|---|---|"]
    for acc, a in rep["accounts"].items():
        p, o = a.get("pess", {}), a.get("opt", {})
        f = lambda v: "n/a" if v is None else f"{v:+.2%}"
        L.append(f"| {acc} | {a['broker']} | {p.get('equity', 'n/a')} | {f(p.get('ret_today'))} | {f(p.get('ret_total'))} "
                 f"| {f(o.get('ret_total'))} | {f(p.get('max_drawdown'))} | {a['closed_trades']} | {a['open_positions']} |")
    L += ["", "## Signals", f"- today: {rep['signals']['today_total']} (traded {rep['signals']['today_traded']})"]
    for r in rep["signals"]["not_traded_reasons"]:
        L.append(f"  - not traded: {r['not_traded_reason']} x{r['n']}")
    o = rep["ops"]
    L += ["", "## Data and ops",
          f"- filings today: {o['filings_today']} (missing acceptance time: {o['filings_missing_accept_ts']})",
          f"- news today: {o['news_today']} | daily bars today: {o['bars_today']} | universe: {o['universe_size']}",
          f"- open data gaps: {o['open_data_gaps']} | kill flags: {o['kill_flags'] or 'none'}", "", "| job | status | runs | last |",
          "|---|---|---|---|"]
    L += [f"| {j['job']} | {j['status']} | {j['n']} | {j['last']} |" for j in o["jobs_24h"]]
    if rep["risk_events"]:
        L += ["", "## Risk events"] + [f"- {r['ts']} {r['account_id']} {r['kind']}: {r['detail']}" for r in rep["risk_events"]]
    return "\n".join(L) + "\n"


def write(con, settings, r_date: str, out_dir: Path | None = None) -> Path:
    rep = build(con, settings, r_date)
    out_dir = out_dir or (PROJECT_ROOT / "reports" / "daily")
    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / f"{r_date}.json").write_text(json.dumps(rep, indent=2, default=str))
    p = out_dir / f"{r_date}.md"
    p.write_text(to_markdown(rep))
    return p
